FROM python:3.6

WORKDIR /opt/docker_test
COPY . /opt/docker_test

RUN pip install Jinja2==2.10
RUN pip install numpy==1.15.4
RUN pip install pandas==0.23.4
RUN pip install psycopg2==2.7.6.1
RUN pip install scikit-learn==0.20.0
RUN pip install SQLAlchemy==1.2.14
RUN pip install click
RUN pip install nltk